project_id = "cqbewlffoosoexbgldqh"

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.google-calendar-auth-callback]
verify_jwt = false

[functions.evolution-webhook]
verify_jwt = false

[functions.ai-reply]
verify_jwt = false

[functions.send-whatsapp-message]
verify_jwt = false

[functions.manage-evolution]
verify_jwt = false

[functions.sync-inbox-messages]
verify_jwt = false